channels:
    - conda-forge
    - bioconda

dependencies:
    # Example command line software
    - pigz=2.6

    # Example Python packages
    - python 
    - argparse=1.4.0

    # Example R packages
    - r-base
    - r-tidyverse
    - r-ggplot2
    - r-dplyr
    - r-plotly
    - r-dt
    - r-crosstalk
    - r-scales
    - r-ggpubr
    - r-ggrepel
    - r-ggthemes
    - bioconductor-phyloseq
    - bioconductor-deseq2
    - bioconductor-limma
